name: build
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
      - uses: actions/setup-node@v2
        with:
          node-version: 19   
      - run: pnpm run setup
      - run: pnpm run lint:ci

  build-SSR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
      - uses: actions/setup-node@v2
        with:
          node-version: 19
      - run: git submodule update --init --recursive    
      - run: pnpm run setup
      - run: pnpm run build
        env:
          INSVEX_HOST: ''
          INSVEX_PORT: ''
          INSVEX_HOST_DIR_MAP: '{ "*": "." }'
          INSVEX_ALLOWED_DIRS: '*'
          INSVEX_THUMB_DIR: thumbs
          INSVEX_THUMB_SIZE: 256
          INSVEX_BUILDCONFIG_SPA: false
          INSVEX_BUILDCONFIG_SPA_EXCLUDED_FILES: ''
          INSVEX_BUILDCONFIG_DIRECTORY_INDEX_NAME: ''
          INSVEX_BUILDCONFIG_SPA_FULL_IMAGE_THUMBS: false
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: SSR
          path: backend/dist
          retention-days: 30

  build-SPA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
      - uses: actions/setup-node@v2
        with:
          node-version: 19
      - run: git submodule update --init --recursive    
      - run: pnpm run setup
      - run: pnpm run build
        env:
          INSVEX_HOST: ''
          INSVEX_PORT: ''
          INSVEX_HOST_DIR_MAP: '{ "*": "." }'
          INSVEX_ALLOWED_DIRS: '*'
          INSVEX_THUMB_DIR: thumbs
          INSVEX_THUMB_SIZE: 256
          INSVEX_BUILDCONFIG_SPA: 'true'
          INSVEX_BUILDCONFIG_SPA_EXCLUDED_FILES: ''
          INSVEX_BUILDCONFIG_DIRECTORY_INDEX_NAME: ''
          INSVEX_BUILDCONFIG_SPA_FULL_IMAGE_THUMBS: false
      - run: rm -rf backend/dist/frontend
      - name: 'Upload Artifact (API)'
        uses: actions/upload-artifact@v3
        with:
          name: SPA-API
          path: backend/dist
          retention-days: 30
      - name: 'Upload Artifact (SPA)'
        uses: actions/upload-artifact@v3
        with:
          name: SPA
          path: frontend/build
          retention-days: 30

  build-SPA-NginX-AUTOINDEX:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
      - uses: actions/setup-node@v2
        with:
          node-version: 19
      - run: git submodule update --init --recursive    
      - run: pnpm run setup
      - run: pnpm run build:spa
        env:
          INSVEX_HOST: ''
          INSVEX_PORT: ''
          INSVEX_HOST_DIR_MAP: '{ "*": "." }'
          INSVEX_ALLOWED_DIRS: '*'
          INSVEX_THUMB_DIR: thumbs
          INSVEX_THUMB_SIZE: 256
          INSVEX_BUILDCONFIG_SPA: 'true'
          INSVEX_BUILDCONFIG_SPA_EXCLUDED_FILES: ''
          INSVEX_BUILDCONFIG_DIRECTORY_INDEX_NAME: 'index.json'
          INSVEX_BUILDCONFIG_SPA_FULL_IMAGE_THUMBS: false
      - name: 'Upload Artifact (SPA-AUTOINDEX)'
        uses: actions/upload-artifact@v3
        with:
          name: SPA-NginX-AUTOINDEX
          path: frontend/build
          retention-days: 30